using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Blazor.Models
{
    public enum BootstrapIcon 
    {
        [Description("alarm-fill")]
        ALARM_FILL,
        [Description("alarm")]
        ALARM,
        [Description("align-bottom")]
        ALIGN_BOTTOM,
        [Description("align-center")]
        ALIGN_CENTER,
        [Description("align-end")]
        ALIGN_END,
        [Description("align-middle")]
        ALIGN_MIDDLE,
        [Description("align-start")]
        ALIGN_START,
        [Description("align-top")]
        ALIGN_TOP,
        [Description("alt")]
        ALT,
        [Description("app-indicator")]
        APP_INDICATOR,
        [Description("app")]
        APP,
        [Description("archive-fill")]
        ARCHIVE_FILL,
        [Description("archive")]
        ARCHIVE,
        [Description("arrow-90deg-down")]
        ARROW_90DEG_DOWN,
        [Description("arrow-90deg-left")]
        ARROW_90DEG_LEFT,
        [Description("arrow-90deg-right")]
        ARROW_90DEG_RIGHT,
        [Description("arrow-90deg-up")]
        ARROW_90DEG_UP,
        [Description("arrow-bar-down")]
        ARROW_BAR_DOWN,
        [Description("arrow-bar-left")]
        ARROW_BAR_LEFT,
        [Description("arrow-bar-right")]
        ARROW_BAR_RIGHT,
        [Description("arrow-bar-up")]
        ARROW_BAR_UP,
        [Description("arrow-clockwise")]
        ARROW_CLOCKWISE,
        [Description("arrow-counterclockwise")]
        ARROW_COUNTERCLOCKWISE,
        [Description("arrow-down-circle-fill")]
        ARROW_DOWN_CIRCLE_FILL,
        [Description("arrow-down-circle")]
        ARROW_DOWN_CIRCLE,
        [Description("arrow-down-left-circle-fill")]
        ARROW_DOWN_LEFT_CIRCLE_FILL,
        [Description("arrow-down-left-circle")]
        ARROW_DOWN_LEFT_CIRCLE,
        [Description("arrow-down-left-square-fill")]
        ARROW_DOWN_LEFT_SQUARE_FILL,
        [Description("arrow-down-left-square")]
        ARROW_DOWN_LEFT_SQUARE,
        [Description("arrow-down-left")]
        ARROW_DOWN_LEFT,
        [Description("arrow-down-right-circle-fill")]
        ARROW_DOWN_RIGHT_CIRCLE_FILL,
        [Description("arrow-down-right-circle")]
        ARROW_DOWN_RIGHT_CIRCLE,
        [Description("arrow-down-right-square-fill")]
        ARROW_DOWN_RIGHT_SQUARE_FILL,
        [Description("arrow-down-right-square")]
        ARROW_DOWN_RIGHT_SQUARE,
        [Description("arrow-down-right")]
        ARROW_DOWN_RIGHT,
        [Description("arrow-down-short")]
        ARROW_DOWN_SHORT,
        [Description("arrow-down-square-fill")]
        ARROW_DOWN_SQUARE_FILL,
        [Description("arrow-down-square")]
        ARROW_DOWN_SQUARE,
        [Description("arrow-down-up")]
        ARROW_DOWN_UP,
        [Description("arrow-down")]
        ARROW_DOWN,
        [Description("arrow-left-circle-fill")]
        ARROW_LEFT_CIRCLE_FILL,
        [Description("arrow-left-circle")]
        ARROW_LEFT_CIRCLE,
        [Description("arrow-left-right")]
        ARROW_LEFT_RIGHT,
        [Description("arrow-left-short")]
        ARROW_LEFT_SHORT,
        [Description("arrow-left-square-fill")]
        ARROW_LEFT_SQUARE_FILL,
        [Description("arrow-left-square")]
        ARROW_LEFT_SQUARE,
        [Description("arrow-left")]
        ARROW_LEFT,
        [Description("arrow-repeat")]
        ARROW_REPEAT,
        [Description("arrow-return-left")]
        ARROW_RETURN_LEFT,
        [Description("arrow-return-right")]
        ARROW_RETURN_RIGHT,
        [Description("arrow-right-circle-fill")]
        ARROW_RIGHT_CIRCLE_FILL,
        [Description("arrow-right-circle")]
        ARROW_RIGHT_CIRCLE,
        [Description("arrow-right-short")]
        ARROW_RIGHT_SHORT,
        [Description("arrow-right-square-fill")]
        ARROW_RIGHT_SQUARE_FILL,
        [Description("arrow-right-square")]
        ARROW_RIGHT_SQUARE,
        [Description("arrow-right")]
        ARROW_RIGHT,
        [Description("arrow-up-circle-fill")]
        ARROW_UP_CIRCLE_FILL,
        [Description("arrow-up-circle")]
        ARROW_UP_CIRCLE,
        [Description("arrow-up-left-circle-fill")]
        ARROW_UP_LEFT_CIRCLE_FILL,
        [Description("arrow-up-left-circle")]
        ARROW_UP_LEFT_CIRCLE,
        [Description("arrow-up-left-square-fill")]
        ARROW_UP_LEFT_SQUARE_FILL,
        [Description("arrow-up-left-square")]
        ARROW_UP_LEFT_SQUARE,
        [Description("arrow-up-left")]
        ARROW_UP_LEFT,
        [Description("arrow-up-right-circle-fill")]
        ARROW_UP_RIGHT_CIRCLE_FILL,
        [Description("arrow-up-right-circle")]
        ARROW_UP_RIGHT_CIRCLE,
        [Description("arrow-up-right-square-fill")]
        ARROW_UP_RIGHT_SQUARE_FILL,
        [Description("arrow-up-right-square")]
        ARROW_UP_RIGHT_SQUARE,
        [Description("arrow-up-right")]
        ARROW_UP_RIGHT,
        [Description("arrow-up-short")]
        ARROW_UP_SHORT,
        [Description("arrow-up-square-fill")]
        ARROW_UP_SQUARE_FILL,
        [Description("arrow-up-square")]
        ARROW_UP_SQUARE,
        [Description("arrow-up")]
        ARROW_UP,
        [Description("arrows-angle-contract")]
        ARROWS_ANGLE_CONTRACT,
        [Description("arrows-angle-expand")]
        ARROWS_ANGLE_EXPAND,
        [Description("arrows-collapse")]
        ARROWS_COLLAPSE,
        [Description("arrows-expand")]
        ARROWS_EXPAND,
        [Description("arrows-fullscreen")]
        ARROWS_FULLSCREEN,
        [Description("arrows-move")]
        ARROWS_MOVE,
        [Description("aspect-ratio-fill")]
        ASPECT_RATIO_FILL,
        [Description("aspect-ratio")]
        ASPECT_RATIO,
        [Description("asterisk")]
        ASTERISK,
        [Description("at")]
        AT,
        [Description("award-fill")]
        AWARD_FILL,
        [Description("award")]
        AWARD,
        [Description("back")]
        BACK,
        [Description("backspace-fill")]
        BACKSPACE_FILL,
        [Description("backspace-reverse-fill")]
        BACKSPACE_REVERSE_FILL,
        [Description("backspace-reverse")]
        BACKSPACE_REVERSE,
        [Description("backspace")]
        BACKSPACE,
        [Description("badge-3d-fill")]
        BADGE_3D_FILL,
        [Description("badge-3d")]
        BADGE_3D,
        [Description("badge-4k-fill")]
        BADGE_4K_FILL,
        [Description("badge-4k")]
        BADGE_4K,
        [Description("badge-8k-fill")]
        BADGE_8K_FILL,
        [Description("badge-8k")]
        BADGE_8K,
        [Description("badge-ad-fill")]
        BADGE_AD_FILL,
        [Description("badge-ad")]
        BADGE_AD,
        [Description("badge-ar-fill")]
        BADGE_AR_FILL,
        [Description("badge-ar")]
        BADGE_AR,
        [Description("badge-cc-fill")]
        BADGE_CC_FILL,
        [Description("badge-cc")]
        BADGE_CC,
        [Description("badge-hd-fill")]
        BADGE_HD_FILL,
        [Description("badge-hd")]
        BADGE_HD,
        [Description("badge-tm-fill")]
        BADGE_TM_FILL,
        [Description("badge-tm")]
        BADGE_TM,
        [Description("badge-vo-fill")]
        BADGE_VO_FILL,
        [Description("badge-vo")]
        BADGE_VO,
        [Description("badge-vr-fill")]
        BADGE_VR_FILL,
        [Description("badge-vr")]
        BADGE_VR,
        [Description("badge-wc-fill")]
        BADGE_WC_FILL,
        [Description("badge-wc")]
        BADGE_WC,
        [Description("bag-check-fill")]
        BAG_CHECK_FILL,
        [Description("bag-check")]
        BAG_CHECK,
        [Description("bag-dash-fill")]
        BAG_DASH_FILL,
        [Description("bag-dash")]
        BAG_DASH,
        [Description("bag-fill")]
        BAG_FILL,
        [Description("bag-plus-fill")]
        BAG_PLUS_FILL,
        [Description("bag-plus")]
        BAG_PLUS,
        [Description("bag-x-fill")]
        BAG_X_FILL,
        [Description("bag-x")]
        BAG_X,
        [Description("bag")]
        BAG,
        [Description("bar-chart-fill")]
        BAR_CHART_FILL,
        [Description("bar-chart-line-fill")]
        BAR_CHART_LINE_FILL,
        [Description("bar-chart-line")]
        BAR_CHART_LINE,
        [Description("bar-chart-steps")]
        BAR_CHART_STEPS,
        [Description("bar-chart")]
        BAR_CHART,
        [Description("basket-fill")]
        BASKET_FILL,
        [Description("basket")]
        BASKET,
        [Description("basket2-fill")]
        BASKET2_FILL,
        [Description("basket2")]
        BASKET2,
        [Description("basket3-fill")]
        BASKET3_FILL,
        [Description("basket3")]
        BASKET3,
        [Description("battery-charging")]
        BATTERY_CHARGING,
        [Description("battery-full")]
        BATTERY_FULL,
        [Description("battery-half")]
        BATTERY_HALF,
        [Description("battery")]
        BATTERY,
        [Description("bell-fill")]
        BELL_FILL,
        [Description("bell")]
        BELL,
        [Description("bezier")]
        BEZIER,
        [Description("bezier2")]
        BEZIER2,
        [Description("bicycle")]
        BICYCLE,
        [Description("binoculars-fill")]
        BINOCULARS_FILL,
        [Description("binoculars")]
        BINOCULARS,
        [Description("blockquote-left")]
        BLOCKQUOTE_LEFT,
        [Description("blockquote-right")]
        BLOCKQUOTE_RIGHT,
        [Description("book-fill")]
        BOOK_FILL,
        [Description("book-half")]
        BOOK_HALF,
        [Description("book")]
        BOOK,
        [Description("bookmark-check-fill")]
        BOOKMARK_CHECK_FILL,
        [Description("bookmark-check")]
        BOOKMARK_CHECK,
        [Description("bookmark-dash-fill")]
        BOOKMARK_DASH_FILL,
        [Description("bookmark-dash")]
        BOOKMARK_DASH,
        [Description("bookmark-fill")]
        BOOKMARK_FILL,
        [Description("bookmark-heart-fill")]
        BOOKMARK_HEART_FILL,
        [Description("bookmark-heart")]
        BOOKMARK_HEART,
        [Description("bookmark-plus-fill")]
        BOOKMARK_PLUS_FILL,
        [Description("bookmark-plus")]
        BOOKMARK_PLUS,
        [Description("bookmark-star-fill")]
        BOOKMARK_STAR_FILL,
        [Description("bookmark-star")]
        BOOKMARK_STAR,
        [Description("bookmark-x-fill")]
        BOOKMARK_X_FILL,
        [Description("bookmark-x")]
        BOOKMARK_X,
        [Description("bookmark")]
        BOOKMARK,
        [Description("bookmarks-fill")]
        BOOKMARKS_FILL,
        [Description("bookmarks")]
        BOOKMARKS,
        [Description("bookshelf")]
        BOOKSHELF,
        [Description("bootstrap-fill")]
        BOOTSTRAP_FILL,
        [Description("bootstrap-reboot")]
        BOOTSTRAP_REBOOT,
        [Description("bootstrap")]
        BOOTSTRAP,
        [Description("border-all")]
        BORDER_ALL,
        [Description("border-bottom")]
        BORDER_BOTTOM,
        [Description("border-center")]
        BORDER_CENTER,
        [Description("border-inner")]
        BORDER_INNER,
        [Description("border-left")]
        BORDER_LEFT,
        [Description("border-middle")]
        BORDER_MIDDLE,
        [Description("border-outer")]
        BORDER_OUTER,
        [Description("border-right")]
        BORDER_RIGHT,
        [Description("border-style")]
        BORDER_STYLE,
        [Description("border-top")]
        BORDER_TOP,
        [Description("border-width")]
        BORDER_WIDTH,
        [Description("border")]
        BORDER,
        [Description("bounding-box-circles")]
        BOUNDING_BOX_CIRCLES,
        [Description("bounding-box")]
        BOUNDING_BOX,
        [Description("box-arrow-down-left")]
        BOX_ARROW_DOWN_LEFT,
        [Description("box-arrow-down-right")]
        BOX_ARROW_DOWN_RIGHT,
        [Description("box-arrow-down")]
        BOX_ARROW_DOWN,
        [Description("box-arrow-in-down-left")]
        BOX_ARROW_IN_DOWN_LEFT,
        [Description("box-arrow-in-down-right")]
        BOX_ARROW_IN_DOWN_RIGHT,
        [Description("box-arrow-in-down")]
        BOX_ARROW_IN_DOWN,
        [Description("box-arrow-in-left")]
        BOX_ARROW_IN_LEFT,
        [Description("box-arrow-in-right")]
        BOX_ARROW_IN_RIGHT,
        [Description("box-arrow-in-up-left")]
        BOX_ARROW_IN_UP_LEFT,
        [Description("box-arrow-in-up-right")]
        BOX_ARROW_IN_UP_RIGHT,
        [Description("box-arrow-in-up")]
        BOX_ARROW_IN_UP,
        [Description("box-arrow-left")]
        BOX_ARROW_LEFT,
        [Description("box-arrow-right")]
        BOX_ARROW_RIGHT,
        [Description("box-arrow-up-left")]
        BOX_ARROW_UP_LEFT,
        [Description("box-arrow-up-right")]
        BOX_ARROW_UP_RIGHT,
        [Description("box-arrow-up")]
        BOX_ARROW_UP,
        [Description("box-seam")]
        BOX_SEAM,
        [Description("box")]
        BOX,
        [Description("braces")]
        BRACES,
        [Description("bricks")]
        BRICKS,
        [Description("briefcase-fill")]
        BRIEFCASE_FILL,
        [Description("briefcase")]
        BRIEFCASE,
        [Description("brightness-alt-high-fill")]
        BRIGHTNESS_ALT_HIGH_FILL,
        [Description("brightness-alt-high")]
        BRIGHTNESS_ALT_HIGH,
        [Description("brightness-alt-low-fill")]
        BRIGHTNESS_ALT_LOW_FILL,
        [Description("brightness-alt-low")]
        BRIGHTNESS_ALT_LOW,
        [Description("brightness-high-fill")]
        BRIGHTNESS_HIGH_FILL,
        [Description("brightness-high")]
        BRIGHTNESS_HIGH,
        [Description("brightness-low-fill")]
        BRIGHTNESS_LOW_FILL,
        [Description("brightness-low")]
        BRIGHTNESS_LOW,
        [Description("broadcast-pin")]
        BROADCAST_PIN,
        [Description("broadcast")]
        BROADCAST,
        [Description("brush-fill")]
        BRUSH_FILL,
        [Description("brush")]
        BRUSH,
        [Description("bucket-fill")]
        BUCKET_FILL,
        [Description("bucket")]
        BUCKET,
        [Description("bug-fill")]
        BUG_FILL,
        [Description("bug")]
        BUG,
        [Description("building")]
        BUILDING,
        [Description("bullseye")]
        BULLSEYE,
        [Description("calculator-fill")]
        CALCULATOR_FILL,
        [Description("calculator")]
        CALCULATOR,
        [Description("calendar-check-fill")]
        CALENDAR_CHECK_FILL,
        [Description("calendar-check")]
        CALENDAR_CHECK,
        [Description("calendar-date-fill")]
        CALENDAR_DATE_FILL,
        [Description("calendar-date")]
        CALENDAR_DATE,
        [Description("calendar-day-fill")]
        CALENDAR_DAY_FILL,
        [Description("calendar-day")]
        CALENDAR_DAY,
        [Description("calendar-event-fill")]
        CALENDAR_EVENT_FILL,
        [Description("calendar-event")]
        CALENDAR_EVENT,
        [Description("calendar-fill")]
        CALENDAR_FILL,
        [Description("calendar-minus-fill")]
        CALENDAR_MINUS_FILL,
        [Description("calendar-minus")]
        CALENDAR_MINUS,
        [Description("calendar-month-fill")]
        CALENDAR_MONTH_FILL,
        [Description("calendar-month")]
        CALENDAR_MONTH,
        [Description("calendar-plus-fill")]
        CALENDAR_PLUS_FILL,
        [Description("calendar-plus")]
        CALENDAR_PLUS,
        [Description("calendar-range-fill")]
        CALENDAR_RANGE_FILL,
        [Description("calendar-range")]
        CALENDAR_RANGE,
        [Description("calendar-week-fill")]
        CALENDAR_WEEK_FILL,
        [Description("calendar-week")]
        CALENDAR_WEEK,
        [Description("calendar-x-fill")]
        CALENDAR_X_FILL,
        [Description("calendar-x")]
        CALENDAR_X,
        [Description("calendar")]
        CALENDAR,
        [Description("calendar2-check-fill")]
        CALENDAR2_CHECK_FILL,
        [Description("calendar2-check")]
        CALENDAR2_CHECK,
        [Description("calendar2-date-fill")]
        CALENDAR2_DATE_FILL,
        [Description("calendar2-date")]
        CALENDAR2_DATE,
        [Description("calendar2-day-fill")]
        CALENDAR2_DAY_FILL,
        [Description("calendar2-day")]
        CALENDAR2_DAY,
        [Description("calendar2-event-fill")]
        CALENDAR2_EVENT_FILL,
        [Description("calendar2-event")]
        CALENDAR2_EVENT,
        [Description("calendar2-fill")]
        CALENDAR2_FILL,
        [Description("calendar2-minus-fill")]
        CALENDAR2_MINUS_FILL,
        [Description("calendar2-minus")]
        CALENDAR2_MINUS,
        [Description("calendar2-month-fill")]
        CALENDAR2_MONTH_FILL,
        [Description("calendar2-month")]
        CALENDAR2_MONTH,
        [Description("calendar2-plus-fill")]
        CALENDAR2_PLUS_FILL,
        [Description("calendar2-plus")]
        CALENDAR2_PLUS,
        [Description("calendar2-range-fill")]
        CALENDAR2_RANGE_FILL,
        [Description("calendar2-range")]
        CALENDAR2_RANGE,
        [Description("calendar2-week-fill")]
        CALENDAR2_WEEK_FILL,
        [Description("calendar2-week")]
        CALENDAR2_WEEK,
        [Description("calendar2-x-fill")]
        CALENDAR2_X_FILL,
        [Description("calendar2-x")]
        CALENDAR2_X,
        [Description("calendar2")]
        CALENDAR2,
        [Description("calendar3-event-fill")]
        CALENDAR3_EVENT_FILL,
        [Description("calendar3-event")]
        CALENDAR3_EVENT,
        [Description("calendar3-fill")]
        CALENDAR3_FILL,
        [Description("calendar3-range-fill")]
        CALENDAR3_RANGE_FILL,
        [Description("calendar3-range")]
        CALENDAR3_RANGE,
        [Description("calendar3-week-fill")]
        CALENDAR3_WEEK_FILL,
        [Description("calendar3-week")]
        CALENDAR3_WEEK,
        [Description("calendar3")]
        CALENDAR3,
        [Description("calendar4-event")]
        CALENDAR4_EVENT,
        [Description("calendar4-range")]
        CALENDAR4_RANGE,
        [Description("calendar4-week")]
        CALENDAR4_WEEK,
        [Description("calendar4")]
        CALENDAR4,
        [Description("camera-fill")]
        CAMERA_FILL,
        [Description("camera-reels-fill")]
        CAMERA_REELS_FILL,
        [Description("camera-reels")]
        CAMERA_REELS,
        [Description("camera-video-fill")]
        CAMERA_VIDEO_FILL,
        [Description("camera-video-off-fill")]
        CAMERA_VIDEO_OFF_FILL,
        [Description("camera-video-off")]
        CAMERA_VIDEO_OFF,
        [Description("camera-video")]
        CAMERA_VIDEO,
        [Description("camera")]
        CAMERA,
        [Description("camera2")]
        CAMERA2,
        [Description("capslock-fill")]
        CAPSLOCK_FILL,
        [Description("capslock")]
        CAPSLOCK,
        [Description("card-checklist")]
        CARD_CHECKLIST,
        [Description("card-heading")]
        CARD_HEADING,
        [Description("card-image")]
        CARD_IMAGE,
        [Description("card-list")]
        CARD_LIST,
        [Description("card-text")]
        CARD_TEXT,
        [Description("caret-down-fill")]
        CARET_DOWN_FILL,
        [Description("caret-down-square-fill")]
        CARET_DOWN_SQUARE_FILL,
        [Description("caret-down-square")]
        CARET_DOWN_SQUARE,
        [Description("caret-down")]
        CARET_DOWN,
        [Description("caret-left-fill")]
        CARET_LEFT_FILL,
        [Description("caret-left-square-fill")]
        CARET_LEFT_SQUARE_FILL,
        [Description("caret-left-square")]
        CARET_LEFT_SQUARE,
        [Description("caret-left")]
        CARET_LEFT,
        [Description("caret-right-fill")]
        CARET_RIGHT_FILL,
        [Description("caret-right-square-fill")]
        CARET_RIGHT_SQUARE_FILL,
        [Description("caret-right-square")]
        CARET_RIGHT_SQUARE,
        [Description("caret-right")]
        CARET_RIGHT,
        [Description("caret-up-fill")]
        CARET_UP_FILL,
        [Description("caret-up-square-fill")]
        CARET_UP_SQUARE_FILL,
        [Description("caret-up-square")]
        CARET_UP_SQUARE,
        [Description("caret-up")]
        CARET_UP,
        [Description("cart-check-fill")]
        CART_CHECK_FILL,
        [Description("cart-check")]
        CART_CHECK,
        [Description("cart-dash-fill")]
        CART_DASH_FILL,
        [Description("cart-dash")]
        CART_DASH,
        [Description("cart-fill")]
        CART_FILL,
        [Description("cart-plus-fill")]
        CART_PLUS_FILL,
        [Description("cart-plus")]
        CART_PLUS,
        [Description("cart-x-fill")]
        CART_X_FILL,
        [Description("cart-x")]
        CART_X,
        [Description("cart")]
        CART,
        [Description("cart2")]
        CART2,
        [Description("cart3")]
        CART3,
        [Description("cart4")]
        CART4,
        [Description("cash-stack")]
        CASH_STACK,
        [Description("cash")]
        CASH,
        [Description("cast")]
        CAST,
        [Description("chat-dots-fill")]
        CHAT_DOTS_FILL,
        [Description("chat-dots")]
        CHAT_DOTS,
        [Description("chat-fill")]
        CHAT_FILL,
        [Description("chat-left-dots-fill")]
        CHAT_LEFT_DOTS_FILL,
        [Description("chat-left-dots")]
        CHAT_LEFT_DOTS,
        [Description("chat-left-fill")]
        CHAT_LEFT_FILL,
        [Description("chat-left-quote-fill")]
        CHAT_LEFT_QUOTE_FILL,
        [Description("chat-left-quote")]
        CHAT_LEFT_QUOTE,
        [Description("chat-left-text-fill")]
        CHAT_LEFT_TEXT_FILL,
        [Description("chat-left-text")]
        CHAT_LEFT_TEXT,
        [Description("chat-left")]
        CHAT_LEFT,
        [Description("chat-quote-fill")]
        CHAT_QUOTE_FILL,
        [Description("chat-quote")]
        CHAT_QUOTE,
        [Description("chat-right-dots-fill")]
        CHAT_RIGHT_DOTS_FILL,
        [Description("chat-right-dots")]
        CHAT_RIGHT_DOTS,
        [Description("chat-right-fill")]
        CHAT_RIGHT_FILL,
        [Description("chat-right-quote-fill")]
        CHAT_RIGHT_QUOTE_FILL,
        [Description("chat-right-quote")]
        CHAT_RIGHT_QUOTE,
        [Description("chat-right-text-fill")]
        CHAT_RIGHT_TEXT_FILL,
        [Description("chat-right-text")]
        CHAT_RIGHT_TEXT,
        [Description("chat-right")]
        CHAT_RIGHT,
        [Description("chat-square-dots-fill")]
        CHAT_SQUARE_DOTS_FILL,
        [Description("chat-square-dots")]
        CHAT_SQUARE_DOTS,
        [Description("chat-square-fill")]
        CHAT_SQUARE_FILL,
        [Description("chat-square-quote-fill")]
        CHAT_SQUARE_QUOTE_FILL,
        [Description("chat-square-quote")]
        CHAT_SQUARE_QUOTE,
        [Description("chat-square-text-fill")]
        CHAT_SQUARE_TEXT_FILL,
        [Description("chat-square-text")]
        CHAT_SQUARE_TEXT,
        [Description("chat-square")]
        CHAT_SQUARE,
        [Description("chat-text-fill")]
        CHAT_TEXT_FILL,
        [Description("chat-text")]
        CHAT_TEXT,
        [Description("chat")]
        CHAT,
        [Description("check-all")]
        CHECK_ALL,
        [Description("check-circle-fill")]
        CHECK_CIRCLE_FILL,
        [Description("check-circle")]
        CHECK_CIRCLE,
        [Description("check-square-fill")]
        CHECK_SQUARE_FILL,
        [Description("check-square")]
        CHECK_SQUARE,
        [Description("check")]
        CHECK,
        [Description("check2-all")]
        CHECK2_ALL,
        [Description("check2-circle")]
        CHECK2_CIRCLE,
        [Description("check2-square")]
        CHECK2_SQUARE,
        [Description("check2")]
        CHECK2,
        [Description("chevron-bar-contract")]
        CHEVRON_BAR_CONTRACT,
        [Description("chevron-bar-down")]
        CHEVRON_BAR_DOWN,
        [Description("chevron-bar-expand")]
        CHEVRON_BAR_EXPAND,
        [Description("chevron-bar-left")]
        CHEVRON_BAR_LEFT,
        [Description("chevron-bar-right")]
        CHEVRON_BAR_RIGHT,
        [Description("chevron-bar-up")]
        CHEVRON_BAR_UP,
        [Description("chevron-compact-down")]
        CHEVRON_COMPACT_DOWN,
        [Description("chevron-compact-left")]
        CHEVRON_COMPACT_LEFT,
        [Description("chevron-compact-right")]
        CHEVRON_COMPACT_RIGHT,
        [Description("chevron-compact-up")]
        CHEVRON_COMPACT_UP,
        [Description("chevron-contract")]
        CHEVRON_CONTRACT,
        [Description("chevron-double-down")]
        CHEVRON_DOUBLE_DOWN,
        [Description("chevron-double-left")]
        CHEVRON_DOUBLE_LEFT,
        [Description("chevron-double-right")]
        CHEVRON_DOUBLE_RIGHT,
        [Description("chevron-double-up")]
        CHEVRON_DOUBLE_UP,
        [Description("chevron-down")]
        CHEVRON_DOWN,
        [Description("chevron-expand")]
        CHEVRON_EXPAND,
        [Description("chevron-left")]
        CHEVRON_LEFT,
        [Description("chevron-right")]
        CHEVRON_RIGHT,
        [Description("chevron-up")]
        CHEVRON_UP,
        [Description("circle-fill")]
        CIRCLE_FILL,
        [Description("circle-half")]
        CIRCLE_HALF,
        [Description("circle-square")]
        CIRCLE_SQUARE,
        [Description("circle")]
        CIRCLE,
        [Description("clipboard-check")]
        CLIPBOARD_CHECK,
        [Description("clipboard-data")]
        CLIPBOARD_DATA,
        [Description("clipboard-minus")]
        CLIPBOARD_MINUS,
        [Description("clipboard-plus")]
        CLIPBOARD_PLUS,
        [Description("clipboard-x")]
        CLIPBOARD_X,
        [Description("clipboard")]
        CLIPBOARD,
        [Description("clock-fill")]
        CLOCK_FILL,
        [Description("clock-history")]
        CLOCK_HISTORY,
        [Description("clock")]
        CLOCK,
        [Description("cloud-arrow-down-fill")]
        CLOUD_ARROW_DOWN_FILL,
        [Description("cloud-arrow-down")]
        CLOUD_ARROW_DOWN,
        [Description("cloud-arrow-up-fill")]
        CLOUD_ARROW_UP_FILL,
        [Description("cloud-arrow-up")]
        CLOUD_ARROW_UP,
        [Description("cloud-check-fill")]
        CLOUD_CHECK_FILL,
        [Description("cloud-check")]
        CLOUD_CHECK,
        [Description("cloud-download-fill")]
        CLOUD_DOWNLOAD_FILL,
        [Description("cloud-download")]
        CLOUD_DOWNLOAD,
        [Description("cloud-drizzle-fill")]
        CLOUD_DRIZZLE_FILL,
        [Description("cloud-drizzle")]
        CLOUD_DRIZZLE,
        [Description("cloud-fill")]
        CLOUD_FILL,
        [Description("cloud-fog-fill")]
        CLOUD_FOG_FILL,
        [Description("cloud-fog")]
        CLOUD_FOG,
        [Description("cloud-fog2-fill")]
        CLOUD_FOG2_FILL,
        [Description("cloud-fog2")]
        CLOUD_FOG2,
        [Description("cloud-hail-fill")]
        CLOUD_HAIL_FILL,
        [Description("cloud-hail")]
        CLOUD_HAIL,
        [Description("cloud-haze-1")]
        CLOUD_HAZE_1,
        [Description("cloud-haze-fill")]
        CLOUD_HAZE_FILL,
        [Description("cloud-haze")]
        CLOUD_HAZE,
        [Description("cloud-haze2-fill")]
        CLOUD_HAZE2_FILL,
        [Description("cloud-lightning-fill")]
        CLOUD_LIGHTNING_FILL,
        [Description("cloud-lightning-rain-fill")]
        CLOUD_LIGHTNING_RAIN_FILL,
        [Description("cloud-lightning-rain")]
        CLOUD_LIGHTNING_RAIN,
        [Description("cloud-lightning")]
        CLOUD_LIGHTNING,
        [Description("cloud-minus-fill")]
        CLOUD_MINUS_FILL,
        [Description("cloud-minus")]
        CLOUD_MINUS,
        [Description("cloud-moon-fill")]
        CLOUD_MOON_FILL,
        [Description("cloud-moon")]
        CLOUD_MOON,
        [Description("cloud-plus-fill")]
        CLOUD_PLUS_FILL,
        [Description("cloud-plus")]
        CLOUD_PLUS,
        [Description("cloud-rain-fill")]
        CLOUD_RAIN_FILL,
        [Description("cloud-rain-heavy-fill")]
        CLOUD_RAIN_HEAVY_FILL,
        [Description("cloud-rain-heavy")]
        CLOUD_RAIN_HEAVY,
        [Description("cloud-rain")]
        CLOUD_RAIN,
        [Description("cloud-slash-fill")]
        CLOUD_SLASH_FILL,
        [Description("cloud-slash")]
        CLOUD_SLASH,
        [Description("cloud-sleet-fill")]
        CLOUD_SLEET_FILL,
        [Description("cloud-sleet")]
        CLOUD_SLEET,
        [Description("cloud-snow-fill")]
        CLOUD_SNOW_FILL,
        [Description("cloud-snow")]
        CLOUD_SNOW,
        [Description("cloud-sun-fill")]
        CLOUD_SUN_FILL,
        [Description("cloud-sun")]
        CLOUD_SUN,
        [Description("cloud-upload-fill")]
        CLOUD_UPLOAD_FILL,
        [Description("cloud-upload")]
        CLOUD_UPLOAD,
        [Description("cloud")]
        CLOUD,
        [Description("clouds-fill")]
        CLOUDS_FILL,
        [Description("clouds")]
        CLOUDS,
        [Description("cloudy-fill")]
        CLOUDY_FILL,
        [Description("cloudy")]
        CLOUDY,
        [Description("code-slash")]
        CODE_SLASH,
        [Description("code-square")]
        CODE_SQUARE,
        [Description("code")]
        CODE,
        [Description("collection-fill")]
        COLLECTION_FILL,
        [Description("collection-play-fill")]
        COLLECTION_PLAY_FILL,
        [Description("collection-play")]
        COLLECTION_PLAY,
        [Description("collection")]
        COLLECTION,
        [Description("columns-gap")]
        COLUMNS_GAP,
        [Description("columns")]
        COLUMNS,
        [Description("command")]
        COMMAND,
        [Description("compass-fill")]
        COMPASS_FILL,
        [Description("compass")]
        COMPASS,
        [Description("cone-striped")]
        CONE_STRIPED,
        [Description("cone")]
        CONE,
        [Description("controller")]
        CONTROLLER,
        [Description("cpu-fill")]
        CPU_FILL,
        [Description("cpu")]
        CPU,
        [Description("credit-card-2-back-fill")]
        CREDIT_CARD_2_BACK_FILL,
        [Description("credit-card-2-back")]
        CREDIT_CARD_2_BACK,
        [Description("credit-card-2-front-fill")]
        CREDIT_CARD_2_FRONT_FILL,
        [Description("credit-card-2-front")]
        CREDIT_CARD_2_FRONT,
        [Description("credit-card-fill")]
        CREDIT_CARD_FILL,
        [Description("credit-card")]
        CREDIT_CARD,
        [Description("crop")]
        CROP,
        [Description("cup-fill")]
        CUP_FILL,
        [Description("cup-straw")]
        CUP_STRAW,
        [Description("cup")]
        CUP,
        [Description("cursor-fill")]
        CURSOR_FILL,
        [Description("cursor-text")]
        CURSOR_TEXT,
        [Description("cursor")]
        CURSOR,
        [Description("dash-circle-dotted")]
        DASH_CIRCLE_DOTTED,
        [Description("dash-circle-fill")]
        DASH_CIRCLE_FILL,
        [Description("dash-circle")]
        DASH_CIRCLE,
        [Description("dash-square-dotted")]
        DASH_SQUARE_DOTTED,
        [Description("dash-square-fill")]
        DASH_SQUARE_FILL,
        [Description("dash-square")]
        DASH_SQUARE,
        [Description("dash")]
        DASH,
        [Description("diagram-2-fill")]
        DIAGRAM_2_FILL,
        [Description("diagram-2")]
        DIAGRAM_2,
        [Description("diagram-3-fill")]
        DIAGRAM_3_FILL,
        [Description("diagram-3")]
        DIAGRAM_3,
        [Description("diamond-fill")]
        DIAMOND_FILL,
        [Description("diamond-half")]
        DIAMOND_HALF,
        [Description("diamond")]
        DIAMOND,
        [Description("dice-1-fill")]
        DICE_1_FILL,
        [Description("dice-1")]
        DICE_1,
        [Description("dice-2-fill")]
        DICE_2_FILL,
        [Description("dice-2")]
        DICE_2,
        [Description("dice-3-fill")]
        DICE_3_FILL,
        [Description("dice-3")]
        DICE_3,
        [Description("dice-4-fill")]
        DICE_4_FILL,
        [Description("dice-4")]
        DICE_4,
        [Description("dice-5-fill")]
        DICE_5_FILL,
        [Description("dice-5")]
        DICE_5,
        [Description("dice-6-fill")]
        DICE_6_FILL,
        [Description("dice-6")]
        DICE_6,
        [Description("disc-fill")]
        DISC_FILL,
        [Description("disc")]
        DISC,
        [Description("discord")]
        DISCORD,
        [Description("display-fill")]
        DISPLAY_FILL,
        [Description("display")]
        DISPLAY,
        [Description("distribute-horizontal")]
        DISTRIBUTE_HORIZONTAL,
        [Description("distribute-vertical")]
        DISTRIBUTE_VERTICAL,
        [Description("door-closed-fill")]
        DOOR_CLOSED_FILL,
        [Description("door-closed")]
        DOOR_CLOSED,
        [Description("door-open-fill")]
        DOOR_OPEN_FILL,
        [Description("door-open")]
        DOOR_OPEN,
        [Description("dot")]
        DOT,
        [Description("download")]
        DOWNLOAD,
        [Description("droplet-fill")]
        DROPLET_FILL,
        [Description("droplet-half")]
        DROPLET_HALF,
        [Description("droplet")]
        DROPLET,
        [Description("earbuds")]
        EARBUDS,
        [Description("easel-fill")]
        EASEL_FILL,
        [Description("easel")]
        EASEL,
        [Description("egg-fill")]
        EGG_FILL,
        [Description("egg-fried")]
        EGG_FRIED,
        [Description("egg")]
        EGG,
        [Description("eject-fill")]
        EJECT_FILL,
        [Description("eject")]
        EJECT,
        [Description("emoji-angry-fill")]
        EMOJI_ANGRY_FILL,
        [Description("emoji-angry")]
        EMOJI_ANGRY,
        [Description("emoji-dizzy-fill")]
        EMOJI_DIZZY_FILL,
        [Description("emoji-dizzy")]
        EMOJI_DIZZY,
        [Description("emoji-expressionless-fill")]
        EMOJI_EXPRESSIONLESS_FILL,
        [Description("emoji-expressionless")]
        EMOJI_EXPRESSIONLESS,
        [Description("emoji-frown-fill")]
        EMOJI_FROWN_FILL,
        [Description("emoji-frown")]
        EMOJI_FROWN,
        [Description("emoji-heart-eyes-fill")]
        EMOJI_HEART_EYES_FILL,
        [Description("emoji-heart-eyes")]
        EMOJI_HEART_EYES,
        [Description("emoji-laughing-fill")]
        EMOJI_LAUGHING_FILL,
        [Description("emoji-laughing")]
        EMOJI_LAUGHING,
        [Description("emoji-neutral-fill")]
        EMOJI_NEUTRAL_FILL,
        [Description("emoji-neutral")]
        EMOJI_NEUTRAL,
        [Description("emoji-smile-fill")]
        EMOJI_SMILE_FILL,
        [Description("emoji-smile-upside-down-fill")]
        EMOJI_SMILE_UPSIDE_DOWN_FILL,
        [Description("emoji-smile-upside-down")]
        EMOJI_SMILE_UPSIDE_DOWN,
        [Description("emoji-smile")]
        EMOJI_SMILE,
        [Description("emoji-sunglasses-fill")]
        EMOJI_SUNGLASSES_FILL,
        [Description("emoji-sunglasses")]
        EMOJI_SUNGLASSES,
        [Description("emoji-wink-fill")]
        EMOJI_WINK_FILL,
        [Description("emoji-wink")]
        EMOJI_WINK,
        [Description("envelope-fill")]
        ENVELOPE_FILL,
        [Description("envelope-open-fill")]
        ENVELOPE_OPEN_FILL,
        [Description("envelope-open")]
        ENVELOPE_OPEN,
        [Description("envelope")]
        ENVELOPE,
        [Description("eraser-fill")]
        ERASER_FILL,
        [Description("eraser")]
        ERASER,
        [Description("exclamation-circle-fill")]
        EXCLAMATION_CIRCLE_FILL,
        [Description("exclamation-circle")]
        EXCLAMATION_CIRCLE,
        [Description("exclamation-diamond-fill")]
        EXCLAMATION_DIAMOND_FILL,
        [Description("exclamation-diamond")]
        EXCLAMATION_DIAMOND,
        [Description("exclamation-octagon-fill")]
        EXCLAMATION_OCTAGON_FILL,
        [Description("exclamation-octagon")]
        EXCLAMATION_OCTAGON,
        [Description("exclamation-square-fill")]
        EXCLAMATION_SQUARE_FILL,
        [Description("exclamation-square")]
        EXCLAMATION_SQUARE,
        [Description("exclamation-triangle-fill")]
        EXCLAMATION_TRIANGLE_FILL,
        [Description("exclamation-triangle")]
        EXCLAMATION_TRIANGLE,
        [Description("exclamation")]
        EXCLAMATION,
        [Description("exclude")]
        EXCLUDE,
        [Description("eye-fill")]
        EYE_FILL,
        [Description("eye-slash-fill")]
        EYE_SLASH_FILL,
        [Description("eye-slash")]
        EYE_SLASH,
        [Description("eye")]
        EYE,
        [Description("eyedropper")]
        EYEDROPPER,
        [Description("eyeglasses")]
        EYEGLASSES,
        [Description("facebook")]
        FACEBOOK,
        [Description("file-arrow-down-fill")]
        FILE_ARROW_DOWN_FILL,
        [Description("file-arrow-down")]
        FILE_ARROW_DOWN,
        [Description("file-arrow-up-fill")]
        FILE_ARROW_UP_FILL,
        [Description("file-arrow-up")]
        FILE_ARROW_UP,
        [Description("file-bar-graph-fill")]
        FILE_BAR_GRAPH_FILL,
        [Description("file-bar-graph")]
        FILE_BAR_GRAPH,
        [Description("file-binary-fill")]
        FILE_BINARY_FILL,
        [Description("file-binary")]
        FILE_BINARY,
        [Description("file-break-fill")]
        FILE_BREAK_FILL,
        [Description("file-break")]
        FILE_BREAK,
        [Description("file-check-fill")]
        FILE_CHECK_FILL,
        [Description("file-check")]
        FILE_CHECK,
        [Description("file-code-fill")]
        FILE_CODE_FILL,
        [Description("file-code")]
        FILE_CODE,
        [Description("file-diff-fill")]
        FILE_DIFF_FILL,
        [Description("file-diff")]
        FILE_DIFF,
        [Description("file-earmark-arrow-down-fill")]
        FILE_EARMARK_ARROW_DOWN_FILL,
        [Description("file-earmark-arrow-down")]
        FILE_EARMARK_ARROW_DOWN,
        [Description("file-earmark-arrow-up-fill")]
        FILE_EARMARK_ARROW_UP_FILL,
        [Description("file-earmark-arrow-up")]
        FILE_EARMARK_ARROW_UP,
        [Description("file-earmark-bar-graph-fill")]
        FILE_EARMARK_BAR_GRAPH_FILL,
        [Description("file-earmark-bar-graph")]
        FILE_EARMARK_BAR_GRAPH,
        [Description("file-earmark-binary-fill")]
        FILE_EARMARK_BINARY_FILL,
        [Description("file-earmark-binary")]
        FILE_EARMARK_BINARY,
        [Description("file-earmark-break-fill")]
        FILE_EARMARK_BREAK_FILL,
        [Description("file-earmark-break")]
        FILE_EARMARK_BREAK,
        [Description("file-earmark-check-fill")]
        FILE_EARMARK_CHECK_FILL,
        [Description("file-earmark-check")]
        FILE_EARMARK_CHECK,
        [Description("file-earmark-code-fill")]
        FILE_EARMARK_CODE_FILL,
        [Description("file-earmark-code")]
        FILE_EARMARK_CODE,
        [Description("file-earmark-diff-fill")]
        FILE_EARMARK_DIFF_FILL,
        [Description("file-earmark-diff")]
        FILE_EARMARK_DIFF,
        [Description("file-earmark-easel-fill")]
        FILE_EARMARK_EASEL_FILL,
        [Description("file-earmark-easel")]
        FILE_EARMARK_EASEL,
        [Description("file-earmark-excel-fill")]
        FILE_EARMARK_EXCEL_FILL,
        [Description("file-earmark-excel")]
        FILE_EARMARK_EXCEL,
        [Description("file-earmark-fill")]
        FILE_EARMARK_FILL,
        [Description("file-earmark-font-fill")]
        FILE_EARMARK_FONT_FILL,
        [Description("file-earmark-font")]
        FILE_EARMARK_FONT,
        [Description("file-earmark-image-fill")]
        FILE_EARMARK_IMAGE_FILL,
        [Description("file-earmark-image")]
        FILE_EARMARK_IMAGE,
        [Description("file-earmark-lock-fill")]
        FILE_EARMARK_LOCK_FILL,
        [Description("file-earmark-lock")]
        FILE_EARMARK_LOCK,
        [Description("file-earmark-lock2-fill")]
        FILE_EARMARK_LOCK2_FILL,
        [Description("file-earmark-lock2")]
        FILE_EARMARK_LOCK2,
        [Description("file-earmark-medical-fill")]
        FILE_EARMARK_MEDICAL_FILL,
        [Description("file-earmark-medical")]
        FILE_EARMARK_MEDICAL,
        [Description("file-earmark-minus-fill")]
        FILE_EARMARK_MINUS_FILL,
        [Description("file-earmark-minus")]
        FILE_EARMARK_MINUS,
        [Description("file-earmark-music-fill")]
        FILE_EARMARK_MUSIC_FILL,
        [Description("file-earmark-music")]
        FILE_EARMARK_MUSIC,
        [Description("file-earmark-person-fill")]
        FILE_EARMARK_PERSON_FILL,
        [Description("file-earmark-person")]
        FILE_EARMARK_PERSON,
        [Description("file-earmark-play-fill")]
        FILE_EARMARK_PLAY_FILL,
        [Description("file-earmark-play")]
        FILE_EARMARK_PLAY,
        [Description("file-earmark-plus-fill")]
        FILE_EARMARK_PLUS_FILL,
        [Description("file-earmark-plus")]
        FILE_EARMARK_PLUS,
        [Description("file-earmark-post-fill")]
        FILE_EARMARK_POST_FILL,
        [Description("file-earmark-post")]
        FILE_EARMARK_POST,
        [Description("file-earmark-ppt-fill")]
        FILE_EARMARK_PPT_FILL,
        [Description("file-earmark-ppt")]
        FILE_EARMARK_PPT,
        [Description("file-earmark-richtext-fill")]
        FILE_EARMARK_RICHTEXT_FILL,
        [Description("file-earmark-richtext")]
        FILE_EARMARK_RICHTEXT,
        [Description("file-earmark-ruled-fill")]
        FILE_EARMARK_RULED_FILL,
        [Description("file-earmark-ruled")]
        FILE_EARMARK_RULED,
        [Description("file-earmark-slides-fill")]
        FILE_EARMARK_SLIDES_FILL,
        [Description("file-earmark-slides")]
        FILE_EARMARK_SLIDES,
        [Description("file-earmark-spreadsheet-fill")]
        FILE_EARMARK_SPREADSHEET_FILL,
        [Description("file-earmark-spreadsheet")]
        FILE_EARMARK_SPREADSHEET,
        [Description("file-earmark-text-fill")]
        FILE_EARMARK_TEXT_FILL,
        [Description("file-earmark-text")]
        FILE_EARMARK_TEXT,
        [Description("file-earmark-word-fill")]
        FILE_EARMARK_WORD_FILL,
        [Description("file-earmark-word")]
        FILE_EARMARK_WORD,
        [Description("file-earmark-x-fill")]
        FILE_EARMARK_X_FILL,
        [Description("file-earmark-x")]
        FILE_EARMARK_X,
        [Description("file-earmark-zip-fill")]
        FILE_EARMARK_ZIP_FILL,
        [Description("file-earmark-zip")]
        FILE_EARMARK_ZIP,
        [Description("file-earmark")]
        FILE_EARMARK,
        [Description("file-easel-fill")]
        FILE_EASEL_FILL,
        [Description("file-easel")]
        FILE_EASEL,
        [Description("file-excel-fill")]
        FILE_EXCEL_FILL,
        [Description("file-excel")]
        FILE_EXCEL,
        [Description("file-fill")]
        FILE_FILL,
        [Description("file-font-fill")]
        FILE_FONT_FILL,
        [Description("file-font")]
        FILE_FONT,
        [Description("file-image-fill")]
        FILE_IMAGE_FILL,
        [Description("file-image")]
        FILE_IMAGE,
        [Description("file-lock-fill")]
        FILE_LOCK_FILL,
        [Description("file-lock")]
        FILE_LOCK,
        [Description("file-lock2-fill")]
        FILE_LOCK2_FILL,
        [Description("file-lock2")]
        FILE_LOCK2,
        [Description("file-medical-fill")]
        FILE_MEDICAL_FILL,
        [Description("file-medical")]
        FILE_MEDICAL,
        [Description("file-minus-fill")]
        FILE_MINUS_FILL,
        [Description("file-minus")]
        FILE_MINUS,
        [Description("file-music-fill")]
        FILE_MUSIC_FILL,
        [Description("file-music")]
        FILE_MUSIC,
        [Description("file-person-fill")]
        FILE_PERSON_FILL,
        [Description("file-person")]
        FILE_PERSON,
        [Description("file-play-fill")]
        FILE_PLAY_FILL,
        [Description("file-play")]
        FILE_PLAY,
        [Description("file-plus-fill")]
        FILE_PLUS_FILL,
        [Description("file-plus")]
        FILE_PLUS,
        [Description("file-post-fill")]
        FILE_POST_FILL,
        [Description("file-post")]
        FILE_POST,
        [Description("file-ppt-fill")]
        FILE_PPT_FILL,
        [Description("file-ppt")]
        FILE_PPT,
        [Description("file-richtext-fill")]
        FILE_RICHTEXT_FILL,
        [Description("file-richtext")]
        FILE_RICHTEXT,
        [Description("file-ruled-fill")]
        FILE_RULED_FILL,
        [Description("file-ruled")]
        FILE_RULED,
        [Description("file-slides-fill")]
        FILE_SLIDES_FILL,
        [Description("file-slides")]
        FILE_SLIDES,
        [Description("file-spreadsheet-fill")]
        FILE_SPREADSHEET_FILL,
        [Description("file-spreadsheet")]
        FILE_SPREADSHEET,
        [Description("file-text-fill")]
        FILE_TEXT_FILL,
        [Description("file-text")]
        FILE_TEXT,
        [Description("file-word-fill")]
        FILE_WORD_FILL,
        [Description("file-word")]
        FILE_WORD,
        [Description("file-x-fill")]
        FILE_X_FILL,
        [Description("file-x")]
        FILE_X,
        [Description("file-zip-fill")]
        FILE_ZIP_FILL,
        [Description("file-zip")]
        FILE_ZIP,
        [Description("file")]
        FILE,
        [Description("files-alt")]
        FILES_ALT,
        [Description("files")]
        FILES,
        [Description("film")]
        FILM,
        [Description("filter-circle-fill")]
        FILTER_CIRCLE_FILL,
        [Description("filter-circle")]
        FILTER_CIRCLE,
        [Description("filter-left")]
        FILTER_LEFT,
        [Description("filter-right")]
        FILTER_RIGHT,
        [Description("filter-square-fill")]
        FILTER_SQUARE_FILL,
        [Description("filter-square")]
        FILTER_SQUARE,
        [Description("filter")]
        FILTER,
        [Description("flag-fill")]
        FLAG_FILL,
        [Description("flag")]
        FLAG,
        [Description("flower1")]
        FLOWER1,
        [Description("flower2")]
        FLOWER2,
        [Description("flower3")]
        FLOWER3,
        [Description("folder-check")]
        FOLDER_CHECK,
        [Description("folder-fill")]
        FOLDER_FILL,
        [Description("folder-minus")]
        FOLDER_MINUS,
        [Description("folder-plus")]
        FOLDER_PLUS,
        [Description("folder-symlink-fill")]
        FOLDER_SYMLINK_FILL,
        [Description("folder-symlink")]
        FOLDER_SYMLINK,
        [Description("folder-x")]
        FOLDER_X,
        [Description("folder")]
        FOLDER,
        [Description("folder2-open")]
        FOLDER2_OPEN,
        [Description("folder2")]
        FOLDER2,
        [Description("fonts")]
        FONTS,
        [Description("forward-fill")]
        FORWARD_FILL,
        [Description("forward")]
        FORWARD,
        [Description("front")]
        FRONT,
        [Description("fullscreen-exit")]
        FULLSCREEN_EXIT,
        [Description("fullscreen")]
        FULLSCREEN,
        [Description("funnel-fill")]
        FUNNEL_FILL,
        [Description("funnel")]
        FUNNEL,
        [Description("gear-fill")]
        GEAR_FILL,
        [Description("gear-wide-connected")]
        GEAR_WIDE_CONNECTED,
        [Description("gear-wide")]
        GEAR_WIDE,
        [Description("gear")]
        GEAR,
        [Description("gem")]
        GEM,
        [Description("geo-alt-fill")]
        GEO_ALT_FILL,
        [Description("geo-alt")]
        GEO_ALT,
        [Description("geo-fill")]
        GEO_FILL,
        [Description("geo")]
        GEO,
        [Description("gift-fill")]
        GIFT_FILL,
        [Description("gift")]
        GIFT,
        [Description("github")]
        GITHUB,
        [Description("globe")]
        GLOBE,
        [Description("globe2")]
        GLOBE2,
        [Description("google")]
        GOOGLE,
        [Description("graph-down")]
        GRAPH_DOWN,
        [Description("graph-up")]
        GRAPH_UP,
        [Description("grid-1x2-fill")]
        GRID_1X2_FILL,
        [Description("grid-1x2")]
        GRID_1X2,
        [Description("grid-3x2-gap-fill")]
        GRID_3X2_GAP_FILL,
        [Description("grid-3x2-gap")]
        GRID_3X2_GAP,
        [Description("grid-3x2")]
        GRID_3X2,
        [Description("grid-3x3-gap-fill")]
        GRID_3X3_GAP_FILL,
        [Description("grid-3x3-gap")]
        GRID_3X3_GAP,
        [Description("grid-3x3")]
        GRID_3X3,
        [Description("grid-fill")]
        GRID_FILL,
        [Description("grid")]
        GRID,
        [Description("grip-horizontal")]
        GRIP_HORIZONTAL,
        [Description("grip-vertical")]
        GRIP_VERTICAL,
        [Description("hammer")]
        HAMMER,
        [Description("hand-index-fill")]
        HAND_INDEX_FILL,
        [Description("hand-index-thumb-fill")]
        HAND_INDEX_THUMB_FILL,
        [Description("hand-index-thumb")]
        HAND_INDEX_THUMB,
        [Description("hand-index")]
        HAND_INDEX,
        [Description("hand-thumbs-down-fill")]
        HAND_THUMBS_DOWN_FILL,
        [Description("hand-thumbs-down")]
        HAND_THUMBS_DOWN,
        [Description("hand-thumbs-up-fill")]
        HAND_THUMBS_UP_FILL,
        [Description("hand-thumbs-up")]
        HAND_THUMBS_UP,
        [Description("handbag-fill")]
        HANDBAG_FILL,
        [Description("handbag")]
        HANDBAG,
        [Description("hash")]
        HASH,
        [Description("hdd-fill")]
        HDD_FILL,
        [Description("hdd-network-fill")]
        HDD_NETWORK_FILL,
        [Description("hdd-network")]
        HDD_NETWORK,
        [Description("hdd-rack-fill")]
        HDD_RACK_FILL,
        [Description("hdd-rack")]
        HDD_RACK,
        [Description("hdd-stack-fill")]
        HDD_STACK_FILL,
        [Description("hdd-stack")]
        HDD_STACK,
        [Description("hdd")]
        HDD,
        [Description("headphones")]
        HEADPHONES,
        [Description("headset")]
        HEADSET,
        [Description("heart-fill")]
        HEART_FILL,
        [Description("heart-half")]
        HEART_HALF,
        [Description("heart")]
        HEART,
        [Description("heptagon-fill")]
        HEPTAGON_FILL,
        [Description("heptagon-half")]
        HEPTAGON_HALF,
        [Description("heptagon")]
        HEPTAGON,
        [Description("hexagon-fill")]
        HEXAGON_FILL,
        [Description("hexagon-half")]
        HEXAGON_HALF,
        [Description("hexagon")]
        HEXAGON,
        [Description("hourglass-bottom")]
        HOURGLASS_BOTTOM,
        [Description("hourglass-split")]
        HOURGLASS_SPLIT,
        [Description("hourglass-top")]
        HOURGLASS_TOP,
        [Description("hourglass")]
        HOURGLASS,
        [Description("house-door-fill")]
        HOUSE_DOOR_FILL,
        [Description("house-door")]
        HOUSE_DOOR,
        [Description("house-fill")]
        HOUSE_FILL,
        [Description("house")]
        HOUSE,
        [Description("hr")]
        HR,
        [Description("hurricane")]
        HURRICANE,
        [Description("image-alt")]
        IMAGE_ALT,
        [Description("image-fill")]
        IMAGE_FILL,
        [Description("image")]
        IMAGE,
        [Description("images")]
        IMAGES,
        [Description("inbox-fill")]
        INBOX_FILL,
        [Description("inbox")]
        INBOX,
        [Description("inboxes-fill")]
        INBOXES_FILL,
        [Description("inboxes")]
        INBOXES,
        [Description("info-circle-fill")]
        INFO_CIRCLE_FILL,
        [Description("info-circle")]
        INFO_CIRCLE,
        [Description("info-square-fill")]
        INFO_SQUARE_FILL,
        [Description("info-square")]
        INFO_SQUARE,
        [Description("info")]
        INFO,
        [Description("input-cursor-text")]
        INPUT_CURSOR_TEXT,
        [Description("input-cursor")]
        INPUT_CURSOR,
        [Description("instagram")]
        INSTAGRAM,
        [Description("intersect")]
        INTERSECT,
        [Description("journal-album")]
        JOURNAL_ALBUM,
        [Description("journal-arrow-down")]
        JOURNAL_ARROW_DOWN,
        [Description("journal-arrow-up")]
        JOURNAL_ARROW_UP,
        [Description("journal-bookmark-fill")]
        JOURNAL_BOOKMARK_FILL,
        [Description("journal-bookmark")]
        JOURNAL_BOOKMARK,
        [Description("journal-check")]
        JOURNAL_CHECK,
        [Description("journal-code")]
        JOURNAL_CODE,
        [Description("journal-medical")]
        JOURNAL_MEDICAL,
        [Description("journal-minus")]
        JOURNAL_MINUS,
        [Description("journal-plus")]
        JOURNAL_PLUS,
        [Description("journal-richtext")]
        JOURNAL_RICHTEXT,
        [Description("journal-text")]
        JOURNAL_TEXT,
        [Description("journal-x")]
        JOURNAL_X,
        [Description("journal")]
        JOURNAL,
        [Description("journals")]
        JOURNALS,
        [Description("joystick")]
        JOYSTICK,
        [Description("justify-left")]
        JUSTIFY_LEFT,
        [Description("justify-right")]
        JUSTIFY_RIGHT,
        [Description("justify")]
        JUSTIFY,
        [Description("kanban-fill")]
        KANBAN_FILL,
        [Description("kanban")]
        KANBAN,
        [Description("key-fill")]
        KEY_FILL,
        [Description("key")]
        KEY,
        [Description("keyboard-fill")]
        KEYBOARD_FILL,
        [Description("keyboard")]
        KEYBOARD,
        [Description("ladder")]
        LADDER,
        [Description("lamp-fill")]
        LAMP_FILL,
        [Description("lamp")]
        LAMP,
        [Description("laptop-fill")]
        LAPTOP_FILL,
        [Description("laptop")]
        LAPTOP,
        [Description("layer-backward")]
        LAYER_BACKWARD,
        [Description("layer-forward")]
        LAYER_FORWARD,
        [Description("layers-fill")]
        LAYERS_FILL,
        [Description("layers-half")]
        LAYERS_HALF,
        [Description("layers")]
        LAYERS,
        [Description("layout-sidebar-inset-reverse")]
        LAYOUT_SIDEBAR_INSET_REVERSE,
        [Description("layout-sidebar-inset")]
        LAYOUT_SIDEBAR_INSET,
        [Description("layout-sidebar-reverse")]
        LAYOUT_SIDEBAR_REVERSE,
        [Description("layout-sidebar")]
        LAYOUT_SIDEBAR,
        [Description("layout-split")]
        LAYOUT_SPLIT,
        [Description("layout-text-sidebar-reverse")]
        LAYOUT_TEXT_SIDEBAR_REVERSE,
        [Description("layout-text-sidebar")]
        LAYOUT_TEXT_SIDEBAR,
        [Description("layout-text-window-reverse")]
        LAYOUT_TEXT_WINDOW_REVERSE,
        [Description("layout-text-window")]
        LAYOUT_TEXT_WINDOW,
        [Description("layout-three-columns")]
        LAYOUT_THREE_COLUMNS,
        [Description("layout-wtf")]
        LAYOUT_WTF,
        [Description("life-preserver")]
        LIFE_PRESERVER,
        [Description("lightbulb-fill")]
        LIGHTBULB_FILL,
        [Description("lightbulb-off-fill")]
        LIGHTBULB_OFF_FILL,
        [Description("lightbulb-off")]
        LIGHTBULB_OFF,
        [Description("lightbulb")]
        LIGHTBULB,
        [Description("lightning-charge-fill")]
        LIGHTNING_CHARGE_FILL,
        [Description("lightning-charge")]
        LIGHTNING_CHARGE,
        [Description("lightning-fill")]
        LIGHTNING_FILL,
        [Description("lightning")]
        LIGHTNING,
        [Description("link-45deg")]
        LINK_45DEG,
        [Description("link")]
        LINK,
        [Description("linkedin")]
        LINKEDIN,
        [Description("list-check")]
        LIST_CHECK,
        [Description("list-nested")]
        LIST_NESTED,
        [Description("list-ol")]
        LIST_OL,
        [Description("list-stars")]
        LIST_STARS,
        [Description("list-task")]
        LIST_TASK,
        [Description("list-ul")]
        LIST_UL,
        [Description("list")]
        LIST,
        [Description("lock-fill")]
        LOCK_FILL,
        [Description("lock")]
        LOCK,
        [Description("mailbox")]
        MAILBOX,
        [Description("mailbox2")]
        MAILBOX2,
        [Description("map-fill")]
        MAP_FILL,
        [Description("map")]
        MAP,
        [Description("markdown-fill")]
        MARKDOWN_FILL,
        [Description("markdown")]
        MARKDOWN,
        [Description("mask")]
        MASK,
        [Description("megaphone-fill")]
        MEGAPHONE_FILL,
        [Description("megaphone")]
        MEGAPHONE,
        [Description("menu-app-fill")]
        MENU_APP_FILL,
        [Description("menu-app")]
        MENU_APP,
        [Description("menu-button-fill")]
        MENU_BUTTON_FILL,
        [Description("menu-button-wide-fill")]
        MENU_BUTTON_WIDE_FILL,
        [Description("menu-button-wide")]
        MENU_BUTTON_WIDE,
        [Description("menu-button")]
        MENU_BUTTON,
        [Description("menu-down")]
        MENU_DOWN,
        [Description("menu-up")]
        MENU_UP,
        [Description("mic-fill")]
        MIC_FILL,
        [Description("mic-mute-fill")]
        MIC_MUTE_FILL,
        [Description("mic-mute")]
        MIC_MUTE,
        [Description("mic")]
        MIC,
        [Description("minecart-loaded")]
        MINECART_LOADED,
        [Description("minecart")]
        MINECART,
        [Description("moisture")]
        MOISTURE,
        [Description("moon-fill")]
        MOON_FILL,
        [Description("moon-stars-fill")]
        MOON_STARS_FILL,
        [Description("moon-stars")]
        MOON_STARS,
        [Description("moon")]
        MOON,
        [Description("mouse-fill")]
        MOUSE_FILL,
        [Description("mouse")]
        MOUSE,
        [Description("mouse2-fill")]
        MOUSE2_FILL,
        [Description("mouse2")]
        MOUSE2,
        [Description("mouse3-fill")]
        MOUSE3_FILL,
        [Description("mouse3")]
        MOUSE3,
        [Description("music-note-beamed")]
        MUSIC_NOTE_BEAMED,
        [Description("music-note-list")]
        MUSIC_NOTE_LIST,
        [Description("music-note")]
        MUSIC_NOTE,
        [Description("music-player-fill")]
        MUSIC_PLAYER_FILL,
        [Description("music-player")]
        MUSIC_PLAYER,
        [Description("newspaper")]
        NEWSPAPER,
        [Description("node-minus-fill")]
        NODE_MINUS_FILL,
        [Description("node-minus")]
        NODE_MINUS,
        [Description("node-plus-fill")]
        NODE_PLUS_FILL,
        [Description("node-plus")]
        NODE_PLUS,
        [Description("nut-fill")]
        NUT_FILL,
        [Description("nut")]
        NUT,
        [Description("octagon-fill")]
        OCTAGON_FILL,
        [Description("octagon-half")]
        OCTAGON_HALF,
        [Description("octagon")]
        OCTAGON,
        [Description("option")]
        OPTION,
        [Description("outlet")]
        OUTLET,
        [Description("paint-bucket")]
        PAINT_BUCKET,
        [Description("palette-fill")]
        PALETTE_FILL,
        [Description("palette")]
        PALETTE,
        [Description("palette2")]
        PALETTE2,
        [Description("paperclip")]
        PAPERCLIP,
        [Description("paragraph")]
        PARAGRAPH,
        [Description("patch-check-fill")]
        PATCH_CHECK_FILL,
        [Description("patch-check")]
        PATCH_CHECK,
        [Description("patch-exclamation-fill")]
        PATCH_EXCLAMATION_FILL,
        [Description("patch-exclamation")]
        PATCH_EXCLAMATION,
        [Description("patch-minus-fill")]
        PATCH_MINUS_FILL,
        [Description("patch-minus")]
        PATCH_MINUS,
        [Description("patch-plus-fill")]
        PATCH_PLUS_FILL,
        [Description("patch-plus")]
        PATCH_PLUS,
        [Description("patch-question-fill")]
        PATCH_QUESTION_FILL,
        [Description("patch-question")]
        PATCH_QUESTION,
        [Description("pause-btn-fill")]
        PAUSE_BTN_FILL,
        [Description("pause-btn")]
        PAUSE_BTN,
        [Description("pause-circle-fill")]
        PAUSE_CIRCLE_FILL,
        [Description("pause-circle")]
        PAUSE_CIRCLE,
        [Description("pause-fill")]
        PAUSE_FILL,
        [Description("pause")]
        PAUSE,
        [Description("peace-fill")]
        PEACE_FILL,
        [Description("peace")]
        PEACE,
        [Description("pen-fill")]
        PEN_FILL,
        [Description("pen")]
        PEN,
        [Description("pencil-fill")]
        PENCIL_FILL,
        [Description("pencil-square")]
        PENCIL_SQUARE,
        [Description("pencil")]
        PENCIL,
        [Description("pentagon-fill")]
        PENTAGON_FILL,
        [Description("pentagon-half")]
        PENTAGON_HALF,
        [Description("pentagon")]
        PENTAGON,
        [Description("people-fill")]
        PEOPLE_FILL,
        [Description("people")]
        PEOPLE,
        [Description("percent")]
        PERCENT,
        [Description("person-badge-fill")]
        PERSON_BADGE_FILL,
        [Description("person-badge")]
        PERSON_BADGE,
        [Description("person-bounding-box")]
        PERSON_BOUNDING_BOX,
        [Description("person-check-fill")]
        PERSON_CHECK_FILL,
        [Description("person-check")]
        PERSON_CHECK,
        [Description("person-circle")]
        PERSON_CIRCLE,
        [Description("person-dash-fill")]
        PERSON_DASH_FILL,
        [Description("person-dash")]
        PERSON_DASH,
        [Description("person-fill")]
        PERSON_FILL,
        [Description("person-lines-fill")]
        PERSON_LINES_FILL,
        [Description("person-plus-fill")]
        PERSON_PLUS_FILL,
        [Description("person-plus")]
        PERSON_PLUS,
        [Description("person-square")]
        PERSON_SQUARE,
        [Description("person-x-fill")]
        PERSON_X_FILL,
        [Description("person-x")]
        PERSON_X,
        [Description("person")]
        PERSON,
        [Description("phone-fill")]
        PHONE_FILL,
        [Description("phone-landscape-fill")]
        PHONE_LANDSCAPE_FILL,
        [Description("phone-landscape")]
        PHONE_LANDSCAPE,
        [Description("phone-vibrate-fill")]
        PHONE_VIBRATE_FILL,
        [Description("phone-vibrate")]
        PHONE_VIBRATE,
        [Description("phone")]
        PHONE,
        [Description("pie-chart-fill")]
        PIE_CHART_FILL,
        [Description("pie-chart")]
        PIE_CHART,
        [Description("pin-angle-fill")]
        PIN_ANGLE_FILL,
        [Description("pin-angle")]
        PIN_ANGLE,
        [Description("pin-fill")]
        PIN_FILL,
        [Description("pin")]
        PIN,
        [Description("pip-fill")]
        PIP_FILL,
        [Description("pip")]
        PIP,
        [Description("play-btn-fill")]
        PLAY_BTN_FILL,
        [Description("play-btn")]
        PLAY_BTN,
        [Description("play-circle-fill")]
        PLAY_CIRCLE_FILL,
        [Description("play-circle")]
        PLAY_CIRCLE,
        [Description("play-fill")]
        PLAY_FILL,
        [Description("play")]
        PLAY,
        [Description("plug-fill")]
        PLUG_FILL,
        [Description("plug")]
        PLUG,
        [Description("plus-circle-dotted")]
        PLUS_CIRCLE_DOTTED,
        [Description("plus-circle-fill")]
        PLUS_CIRCLE_FILL,
        [Description("plus-circle")]
        PLUS_CIRCLE,
        [Description("plus-square-dotted")]
        PLUS_SQUARE_DOTTED,
        [Description("plus-square-fill")]
        PLUS_SQUARE_FILL,
        [Description("plus-square")]
        PLUS_SQUARE,
        [Description("plus")]
        PLUS,
        [Description("power")]
        POWER,
        [Description("printer-fill")]
        PRINTER_FILL,
        [Description("printer")]
        PRINTER,
        [Description("puzzle-fill")]
        PUZZLE_FILL,
        [Description("puzzle")]
        PUZZLE,
        [Description("question-circle-fill")]
        QUESTION_CIRCLE_FILL,
        [Description("question-circle")]
        QUESTION_CIRCLE,
        [Description("question-diamond-fill")]
        QUESTION_DIAMOND_FILL,
        [Description("question-diamond")]
        QUESTION_DIAMOND,
        [Description("question-octagon-fill")]
        QUESTION_OCTAGON_FILL,
        [Description("question-octagon")]
        QUESTION_OCTAGON,
        [Description("question-square-fill")]
        QUESTION_SQUARE_FILL,
        [Description("question-square")]
        QUESTION_SQUARE,
        [Description("question")]
        QUESTION,
        [Description("rainbow")]
        RAINBOW,
        [Description("receipt-cutoff")]
        RECEIPT_CUTOFF,
        [Description("receipt")]
        RECEIPT,
        [Description("reception-0")]
        RECEPTION_0,
        [Description("reception-1")]
        RECEPTION_1,
        [Description("reception-2")]
        RECEPTION_2,
        [Description("reception-3")]
        RECEPTION_3,
        [Description("reception-4")]
        RECEPTION_4,
        [Description("record-btn-fill")]
        RECORD_BTN_FILL,
        [Description("record-btn")]
        RECORD_BTN,
        [Description("record-circle-fill")]
        RECORD_CIRCLE_FILL,
        [Description("record-circle")]
        RECORD_CIRCLE,
        [Description("record-fill")]
        RECORD_FILL,
        [Description("record")]
        RECORD,
        [Description("record2-fill")]
        RECORD2_FILL,
        [Description("record2")]
        RECORD2,
        [Description("reply-all-fill")]
        REPLY_ALL_FILL,
        [Description("reply-all")]
        REPLY_ALL,
        [Description("reply-fill")]
        REPLY_FILL,
        [Description("reply")]
        REPLY,
        [Description("rss-fill")]
        RSS_FILL,
        [Description("rss")]
        RSS,
        [Description("rulers")]
        RULERS,
        [Description("save-fill")]
        SAVE_FILL,
        [Description("save")]
        SAVE,
        [Description("save2-fill")]
        SAVE2_FILL,
        [Description("save2")]
        SAVE2,
        [Description("scissors")]
        SCISSORS,
        [Description("screwdriver")]
        SCREWDRIVER,
        [Description("search")]
        SEARCH,
        [Description("segmented-nav")]
        SEGMENTED_NAV,
        [Description("server")]
        SERVER,
        [Description("share-fill")]
        SHARE_FILL,
        [Description("share")]
        SHARE,
        [Description("shield-check")]
        SHIELD_CHECK,
        [Description("shield-exclamation")]
        SHIELD_EXCLAMATION,
        [Description("shield-fill-check")]
        SHIELD_FILL_CHECK,
        [Description("shield-fill-exclamation")]
        SHIELD_FILL_EXCLAMATION,
        [Description("shield-fill-minus")]
        SHIELD_FILL_MINUS,
        [Description("shield-fill-plus")]
        SHIELD_FILL_PLUS,
        [Description("shield-fill-x")]
        SHIELD_FILL_X,
        [Description("shield-fill")]
        SHIELD_FILL,
        [Description("shield-lock-fill")]
        SHIELD_LOCK_FILL,
        [Description("shield-lock")]
        SHIELD_LOCK,
        [Description("shield-minus")]
        SHIELD_MINUS,
        [Description("shield-plus")]
        SHIELD_PLUS,
        [Description("shield-shaded")]
        SHIELD_SHADED,
        [Description("shield-slash-fill")]
        SHIELD_SLASH_FILL,
        [Description("shield-slash")]
        SHIELD_SLASH,
        [Description("shield-x")]
        SHIELD_X,
        [Description("shield")]
        SHIELD,
        [Description("shift-fill")]
        SHIFT_FILL,
        [Description("shift")]
        SHIFT,
        [Description("shop-window")]
        SHOP_WINDOW,
        [Description("shop")]
        SHOP,
        [Description("shuffle")]
        SHUFFLE,
        [Description("signpost-2-fill")]
        SIGNPOST_2_FILL,
        [Description("signpost-2")]
        SIGNPOST_2,
        [Description("signpost-fill")]
        SIGNPOST_FILL,
        [Description("signpost-split-fill")]
        SIGNPOST_SPLIT_FILL,
        [Description("signpost-split")]
        SIGNPOST_SPLIT,
        [Description("signpost")]
        SIGNPOST,
        [Description("sim-fill")]
        SIM_FILL,
        [Description("sim")]
        SIM,
        [Description("skip-backward-btn-fill")]
        SKIP_BACKWARD_BTN_FILL,
        [Description("skip-backward-btn")]
        SKIP_BACKWARD_BTN,
        [Description("skip-backward-circle-fill")]
        SKIP_BACKWARD_CIRCLE_FILL,
        [Description("skip-backward-circle")]
        SKIP_BACKWARD_CIRCLE,
        [Description("skip-backward-fill")]
        SKIP_BACKWARD_FILL,
        [Description("skip-backward")]
        SKIP_BACKWARD,
        [Description("skip-end-btn-fill")]
        SKIP_END_BTN_FILL,
        [Description("skip-end-btn")]
        SKIP_END_BTN,
        [Description("skip-end-circle-fill")]
        SKIP_END_CIRCLE_FILL,
        [Description("skip-end-circle")]
        SKIP_END_CIRCLE,
        [Description("skip-end-fill")]
        SKIP_END_FILL,
        [Description("skip-end")]
        SKIP_END,
        [Description("skip-forward-btn-fill")]
        SKIP_FORWARD_BTN_FILL,
        [Description("skip-forward-btn")]
        SKIP_FORWARD_BTN,
        [Description("skip-forward-circle-fill")]
        SKIP_FORWARD_CIRCLE_FILL,
        [Description("skip-forward-circle")]
        SKIP_FORWARD_CIRCLE,
        [Description("skip-forward-fill")]
        SKIP_FORWARD_FILL,
        [Description("skip-forward")]
        SKIP_FORWARD,
        [Description("skip-start-btn-fill")]
        SKIP_START_BTN_FILL,
        [Description("skip-start-btn")]
        SKIP_START_BTN,
        [Description("skip-start-circle-fill")]
        SKIP_START_CIRCLE_FILL,
        [Description("skip-start-circle")]
        SKIP_START_CIRCLE,
        [Description("skip-start-fill")]
        SKIP_START_FILL,
        [Description("skip-start")]
        SKIP_START,
        [Description("slack")]
        SLACK,
        [Description("slash-circle-fill")]
        SLASH_CIRCLE_FILL,
        [Description("slash-circle")]
        SLASH_CIRCLE,
        [Description("slash-square-fill")]
        SLASH_SQUARE_FILL,
        [Description("slash-square")]
        SLASH_SQUARE,
        [Description("slash")]
        SLASH,
        [Description("sliders")]
        SLIDERS,
        [Description("smartwatch")]
        SMARTWATCH,
        [Description("snow")]
        SNOW,
        [Description("snow2")]
        SNOW2,
        [Description("snow3")]
        SNOW3,
        [Description("sort-alpha-down-alt")]
        SORT_ALPHA_DOWN_ALT,
        [Description("sort-alpha-down")]
        SORT_ALPHA_DOWN,
        [Description("sort-alpha-up-alt")]
        SORT_ALPHA_UP_ALT,
        [Description("sort-alpha-up")]
        SORT_ALPHA_UP,
        [Description("sort-down-alt")]
        SORT_DOWN_ALT,
        [Description("sort-down")]
        SORT_DOWN,
        [Description("sort-numeric-down-alt")]
        SORT_NUMERIC_DOWN_ALT,
        [Description("sort-numeric-down")]
        SORT_NUMERIC_DOWN,
        [Description("sort-numeric-up-alt")]
        SORT_NUMERIC_UP_ALT,
        [Description("sort-numeric-up")]
        SORT_NUMERIC_UP,
        [Description("sort-up-alt")]
        SORT_UP_ALT,
        [Description("sort-up")]
        SORT_UP,
        [Description("soundwave")]
        SOUNDWAVE,
        [Description("speaker-fill")]
        SPEAKER_FILL,
        [Description("speaker")]
        SPEAKER,
        [Description("speedometer")]
        SPEEDOMETER,
        [Description("speedometer2")]
        SPEEDOMETER2,
        [Description("spellcheck")]
        SPELLCHECK,
        [Description("square-fill")]
        SQUARE_FILL,
        [Description("square-half")]
        SQUARE_HALF,
        [Description("square")]
        SQUARE,
        [Description("stack")]
        STACK,
        [Description("star-fill")]
        STAR_FILL,
        [Description("star-half")]
        STAR_HALF,
        [Description("star")]
        STAR,
        [Description("stars")]
        STARS,
        [Description("stickies-fill")]
        STICKIES_FILL,
        [Description("stickies")]
        STICKIES,
        [Description("sticky-fill")]
        STICKY_FILL,
        [Description("sticky")]
        STICKY,
        [Description("stop-btn-fill")]
        STOP_BTN_FILL,
        [Description("stop-btn")]
        STOP_BTN,
        [Description("stop-circle-fill")]
        STOP_CIRCLE_FILL,
        [Description("stop-circle")]
        STOP_CIRCLE,
        [Description("stop-fill")]
        STOP_FILL,
        [Description("stop")]
        STOP,
        [Description("stoplights-fill")]
        STOPLIGHTS_FILL,
        [Description("stoplights")]
        STOPLIGHTS,
        [Description("stopwatch-fill")]
        STOPWATCH_FILL,
        [Description("stopwatch")]
        STOPWATCH,
        [Description("subtract")]
        SUBTRACT,
        [Description("suit-club-fill")]
        SUIT_CLUB_FILL,
        [Description("suit-club")]
        SUIT_CLUB,
        [Description("suit-diamond-fill")]
        SUIT_DIAMOND_FILL,
        [Description("suit-diamond")]
        SUIT_DIAMOND,
        [Description("suit-heart-fill")]
        SUIT_HEART_FILL,
        [Description("suit-heart")]
        SUIT_HEART,
        [Description("suit-spade-fill")]
        SUIT_SPADE_FILL,
        [Description("suit-spade")]
        SUIT_SPADE,
        [Description("sun-fill")]
        SUN_FILL,
        [Description("sun")]
        SUN,
        [Description("sunglasses")]
        SUNGLASSES,
        [Description("sunrise-fill")]
        SUNRISE_FILL,
        [Description("sunrise")]
        SUNRISE,
        [Description("sunset-fill")]
        SUNSET_FILL,
        [Description("sunset")]
        SUNSET,
        [Description("symmetry-horizontal")]
        SYMMETRY_HORIZONTAL,
        [Description("symmetry-vertical")]
        SYMMETRY_VERTICAL,
        [Description("table")]
        TABLE,
        [Description("tablet-fill")]
        TABLET_FILL,
        [Description("tablet-landscape-fill")]
        TABLET_LANDSCAPE_FILL,
        [Description("tablet-landscape")]
        TABLET_LANDSCAPE,
        [Description("tablet")]
        TABLET,
        [Description("tag-fill")]
        TAG_FILL,
        [Description("tag")]
        TAG,
        [Description("tags-fill")]
        TAGS_FILL,
        [Description("tags")]
        TAGS,
        [Description("telegram")]
        TELEGRAM,
        [Description("telephone-fill")]
        TELEPHONE_FILL,
        [Description("telephone-forward-fill")]
        TELEPHONE_FORWARD_FILL,
        [Description("telephone-forward")]
        TELEPHONE_FORWARD,
        [Description("telephone-inbound-fill")]
        TELEPHONE_INBOUND_FILL,
        [Description("telephone-inbound")]
        TELEPHONE_INBOUND,
        [Description("telephone-minus-fill")]
        TELEPHONE_MINUS_FILL,
        [Description("telephone-minus")]
        TELEPHONE_MINUS,
        [Description("telephone-outbound-fill")]
        TELEPHONE_OUTBOUND_FILL,
        [Description("telephone-outbound")]
        TELEPHONE_OUTBOUND,
        [Description("telephone-plus-fill")]
        TELEPHONE_PLUS_FILL,
        [Description("telephone-plus")]
        TELEPHONE_PLUS,
        [Description("telephone-x-fill")]
        TELEPHONE_X_FILL,
        [Description("telephone-x")]
        TELEPHONE_X,
        [Description("telephone")]
        TELEPHONE,
        [Description("terminal-fill")]
        TERMINAL_FILL,
        [Description("terminal")]
        TERMINAL,
        [Description("text-center")]
        TEXT_CENTER,
        [Description("text-indent-left")]
        TEXT_INDENT_LEFT,
        [Description("text-indent-right")]
        TEXT_INDENT_RIGHT,
        [Description("text-left")]
        TEXT_LEFT,
        [Description("text-paragraph")]
        TEXT_PARAGRAPH,
        [Description("text-right")]
        TEXT_RIGHT,
        [Description("textarea-resize")]
        TEXTAREA_RESIZE,
        [Description("textarea-t")]
        TEXTAREA_T,
        [Description("textarea")]
        TEXTAREA,
        [Description("thermometer-half")]
        THERMOMETER_HALF,
        [Description("thermometer-high")]
        THERMOMETER_HIGH,
        [Description("thermometer-low")]
        THERMOMETER_LOW,
        [Description("thermometer-snow")]
        THERMOMETER_SNOW,
        [Description("thermometer-sun")]
        THERMOMETER_SUN,
        [Description("thermometer")]
        THERMOMETER,
        [Description("three-dots-vertical")]
        THREE_DOTS_VERTICAL,
        [Description("three-dots")]
        THREE_DOTS,
        [Description("toggle-off")]
        TOGGLE_OFF,
        [Description("toggle-on")]
        TOGGLE_ON,
        [Description("toggle2-off")]
        TOGGLE2_OFF,
        [Description("toggle2-on")]
        TOGGLE2_ON,
        [Description("toggles")]
        TOGGLES,
        [Description("toggles2")]
        TOGGLES2,
        [Description("tools")]
        TOOLS,
        [Description("tornado")]
        TORNADO,
        [Description("trash-fill")]
        TRASH_FILL,
        [Description("trash")]
        TRASH,
        [Description("trash2-fill")]
        TRASH2_FILL,
        [Description("trash2")]
        TRASH2,
        [Description("tree-fill")]
        TREE_FILL,
        [Description("tree")]
        TREE,
        [Description("triangle-fill")]
        TRIANGLE_FILL,
        [Description("triangle-half")]
        TRIANGLE_HALF,
        [Description("triangle")]
        TRIANGLE,
        [Description("trophy-fill")]
        TROPHY_FILL,
        [Description("trophy")]
        TROPHY,
        [Description("tropical-storm")]
        TROPICAL_STORM,
        [Description("truck-flatbed")]
        TRUCK_FLATBED,
        [Description("truck")]
        TRUCK,
        [Description("tsunami")]
        TSUNAMI,
        [Description("tv-fill")]
        TV_FILL,
        [Description("tv")]
        TV,
        [Description("twitch")]
        TWITCH,
        [Description("twitter")]
        TWITTER,
        [Description("type-bold")]
        TYPE_BOLD,
        [Description("type-h1")]
        TYPE_H1,
        [Description("type-h2")]
        TYPE_H2,
        [Description("type-h3")]
        TYPE_H3,
        [Description("type-italic")]
        TYPE_ITALIC,
        [Description("type-strikethrough")]
        TYPE_STRIKETHROUGH,
        [Description("type-underline")]
        TYPE_UNDERLINE,
        [Description("type")]
        TYPE,
        [Description("ui-checks-grid")]
        UI_CHECKS_GRID,
        [Description("ui-checks")]
        UI_CHECKS,
        [Description("ui-radios-grid")]
        UI_RADIOS_GRID,
        [Description("ui-radios")]
        UI_RADIOS,
        [Description("umbrella-fill")]
        UMBRELLA_FILL,
        [Description("umbrella")]
        UMBRELLA,
        [Description("union")]
        UNION,
        [Description("unlock-fill")]
        UNLOCK_FILL,
        [Description("unlock")]
        UNLOCK,
        [Description("upc-scan")]
        UPC_SCAN,
        [Description("upc")]
        UPC,
        [Description("upload")]
        UPLOAD,
        [Description("vector-pen")]
        VECTOR_PEN,
        [Description("view-list")]
        VIEW_LIST,
        [Description("view-stacked")]
        VIEW_STACKED,
        [Description("vinyl-fill")]
        VINYL_FILL,
        [Description("vinyl")]
        VINYL,
        [Description("voicemail")]
        VOICEMAIL,
        [Description("volume-down-fill")]
        VOLUME_DOWN_FILL,
        [Description("volume-down")]
        VOLUME_DOWN,
        [Description("volume-mute-fill")]
        VOLUME_MUTE_FILL,
        [Description("volume-mute")]
        VOLUME_MUTE,
        [Description("volume-off-fill")]
        VOLUME_OFF_FILL,
        [Description("volume-off")]
        VOLUME_OFF,
        [Description("volume-up-fill")]
        VOLUME_UP_FILL,
        [Description("volume-up")]
        VOLUME_UP,
        [Description("vr")]
        VR,
        [Description("wallet-fill")]
        WALLET_FILL,
        [Description("wallet")]
        WALLET,
        [Description("wallet2")]
        WALLET2,
        [Description("watch")]
        WATCH,
        [Description("water")]
        WATER,
        [Description("whatsapp")]
        WHATSAPP,
        [Description("wifi-1")]
        WIFI_1,
        [Description("wifi-2")]
        WIFI_2,
        [Description("wifi-off")]
        WIFI_OFF,
        [Description("wifi")]
        WIFI,
        [Description("wind")]
        WIND,
        [Description("window-dock")]
        WINDOW_DOCK,
        [Description("window-sidebar")]
        WINDOW_SIDEBAR,
        [Description("window")]
        WINDOW,
        [Description("wrench")]
        WRENCH,
        [Description("x-circle-fill")]
        X_CIRCLE_FILL,
        [Description("x-circle")]
        X_CIRCLE,
        [Description("x-diamond-fill")]
        X_DIAMOND_FILL,
        [Description("x-diamond")]
        X_DIAMOND,
        [Description("x-octagon-fill")]
        X_OCTAGON_FILL,
        [Description("x-octagon")]
        X_OCTAGON,
        [Description("x-square-fill")]
        X_SQUARE_FILL,
        [Description("x-square")]
        X_SQUARE,
        [Description("x")]
        X,
        [Description("youtube")]
        YOUTUBE,
        [Description("zoom-in")]
        ZOOM_IN,
        [Description("zoom-out")]
        ZOOM_OUT,
        [Description("bank")]
        BANK,
        [Description("bank2")]
        BANK2,
        [Description("bell-slash-fill")]
        BELL_SLASH_FILL,
        [Description("bell-slash")]
        BELL_SLASH,
        [Description("cash-coin")]
        CASH_COIN,
        [Description("check-lg")]
        CHECK_LG,
        [Description("coin")]
        COIN,
        [Description("currency-bitcoin")]
        CURRENCY_BITCOIN,
        [Description("currency-dollar")]
        CURRENCY_DOLLAR,
        [Description("currency-euro")]
        CURRENCY_EURO,
        [Description("currency-exchange")]
        CURRENCY_EXCHANGE,
        [Description("currency-pound")]
        CURRENCY_POUND,
        [Description("currency-yen")]
        CURRENCY_YEN,
        [Description("dash-lg")]
        DASH_LG,
        [Description("exclamation-lg")]
        EXCLAMATION_LG,
        [Description("file-earmark-pdf-fill")]
        FILE_EARMARK_PDF_FILL,
        [Description("file-earmark-pdf")]
        FILE_EARMARK_PDF,
        [Description("file-pdf-fill")]
        FILE_PDF_FILL,
        [Description("file-pdf")]
        FILE_PDF,
        [Description("gender-ambiguous")]
        GENDER_AMBIGUOUS,
        [Description("gender-female")]
        GENDER_FEMALE,
        [Description("gender-male")]
        GENDER_MALE,
        [Description("gender-trans")]
        GENDER_TRANS,
        [Description("headset-vr")]
        HEADSET_VR,
        [Description("info-lg")]
        INFO_LG,
        [Description("mastodon")]
        MASTODON,
        [Description("messenger")]
        MESSENGER,
        [Description("piggy-bank-fill")]
        PIGGY_BANK_FILL,
        [Description("piggy-bank")]
        PIGGY_BANK,
        [Description("pin-map-fill")]
        PIN_MAP_FILL,
        [Description("pin-map")]
        PIN_MAP,
        [Description("plus-lg")]
        PLUS_LG,
        [Description("question-lg")]
        QUESTION_LG,
        [Description("recycle")]
        RECYCLE,
        [Description("reddit")]
        REDDIT,
        [Description("safe-fill")]
        SAFE_FILL,
        [Description("safe2-fill")]
        SAFE2_FILL,
        [Description("safe2")]
        SAFE2,
        [Description("sd-card-fill")]
        SD_CARD_FILL,
        [Description("sd-card")]
        SD_CARD,
        [Description("skype")]
        SKYPE,
        [Description("slash-lg")]
        SLASH_LG,
        [Description("translate")]
        TRANSLATE,
        [Description("x-lg")]
        X_LG,
        [Description("safe")]
        SAFE
    }

    // ("([a-z0-9\-]+)"): \d+,   ->   [Description($1)] \n $2,
}
